const DEFAULT_OFFSET_PAYLOAD = 0
const DEFAULT_LIMIT = 20
const SORT_ASCENDING = 1
const SORT_DESCENDING = -1
const PAGE_LIMITS = [10, 20, 30, 40, 50]
const DECIMAL_REDIX = 10
const DEFAULT_CURRENT_PAGE = 1
const EXCLUDE_SORT_COLUMNS = ["actions"]
const INTERNAL_ERROR_CODE = "INTERNAL_ERROR"

export {
  DEFAULT_OFFSET_PAYLOAD,
  DEFAULT_LIMIT,
  SORT_ASCENDING,
  SORT_DESCENDING,
  PAGE_LIMITS,
  DECIMAL_REDIX,
  DEFAULT_CURRENT_PAGE,
  EXCLUDE_SORT_COLUMNS,
  INTERNAL_ERROR_CODE,
}
