const DEFAULT_OFFSET_PAYLOAD = 0
const DEFAULT_LIMIT = 20
const DEFAULT_SORT = 1
const PAGE_LIMITS = [10, 20, 30, 40, 50]
const DECIMAL_REDIX = 10
const DEFAULT_CURRENT_PAGE = 1

export { DEFAULT_OFFSET_PAYLOAD, DEFAULT_LIMIT, DEFAULT_SORT, PAGE_LIMITS, DECIMAL_REDIX, DEFAULT_CURRENT_PAGE }
